package model;

import java.util.Objects;

public class Todo {
	
	private String texte;
	private boolean actif;
	private int id;
	
	public Todo(String texte, boolean actif, int id) {
		this.texte = texte;
		this.actif = actif;
		this.id = id;
	}
	
	public Todo(String texte, boolean actif) {
		this.texte = texte;
		this.actif = actif;
		this.id = 1;
	}

	public Todo(String texte, int id) {
		this.texte = texte;
		this.actif = false;
		this.id = id;
	}
	
	public Todo(String texte) {
		this.texte = texte;
		this.actif = false;
		this.id = 1;
	}
	
	
	public Todo() {
		this.texte = "<Todo>";
		this.actif = false;
	}
	
	public String getTexte() {
		return texte;
	}

	public void setTexte(String texte) {
		this.texte = texte;
	}

	public boolean isActif() {
		return actif;
	}

	public void setActif(boolean actif) {
		this.actif = actif;
	}

	@Override
	public int hashCode() {
		return Objects.hash(texte);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Todo other = (Todo) obj;
		return Objects.equals(texte, other.texte);
	}

	public void setId(int autoGeneratedIdFromDatabase) {
		this.id = autoGeneratedIdFromDatabase;
	}

	public int getId() {
		return id;
	}

}
